# Netlify Configuration for Hugo Deployment
[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.121.2"  # Use latest Hugo version
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --buildDrafts"

[context.branch-deploy]
  command = "hugo --buildDrafts"